### PR TITLE
Update kleur

### PR DESCRIPTION
**Pull request by alubbe**
Should be a safe upgrade (v6 compat was restored with 4.0.1)
https://github.com/lukeed/kleur/releases/tag/v4.0.0
https://github.com/lukeed/kleur/releases/tag/v4.0.1

### CODE REVIEW

**Comment by alubbe** [comment]
Since node 13's support ended with the release of 14.0.0, I think this should be fine. And anyone on 13.0-13.6 can upgrade to 13.7-13.14

**Comment by terkelg** [comment]
Sounds like it's safe to update, right @lukeed?

**Comment by lukeed** [comment]
It should be, but you'd be amazed how many people are holding onto stale 13.x versions.

**Comment by g-plane** [comment]
Will the maintainer merge this PR and release a new version? Since PR is approved.

**Pull request merged**
