### PR TITLE
feat: autocomplete multiselect

### PR DESCRIPTION
**Pull request by creatyvtype**
Should handle https://github.com/terkelg/prompts/issues/127
Adds figures 6 figures - arrows and radio on/off
Adds paginated scrolling for long lists in multiselect
Adds radio icons for multiselect (better than blank/check IMO)
Adds autocompleteMultiselect option

### CODE REVIEW

**Comment by lumio** [comment]
Thanks for your PR.
What exactly was the problem with the local `figures.js`?

**Comment by creatyvtype** [comment]
@lumio It was limited to only a handful of symbols, and I found this package added to include way more AND handle the Windows CMD fallbacks. I wanted the multiselect to have radio buttons, which were figures you did not have in the file, as well as using arrows to help provide instructions for the multiselect.

**Comment by terkelg** [comment]
I don't think we should introduce dependencies for this. If you need a few more signatures we can add them to `figures.js`

**Comment by creatyvtype** [comment]
@terkelg this dependency is extremely small and essentially is exactly what you had for the figures. I feel like I would be literally copying from that library to include these icons here. Is it a blocker for you?

**Comment by lumio** [comment]
I agree with @terkelg. Although it was meant in a good way (having the ability to use all supported characters of figures is a nice to have situation), adding a new dependency just for one or two newly used symbols sounds a little overkill to me.
One of `prompts` main goals is to have a minimal dependency footprint. There were a couple of incidents in the past that proved that this is actually a good thing to do.

**Comment by creatyvtype** [comment]
@lumio @terkelg I believe this should do it.

**Comment by terkelg** [comment]
Does this look good to you @lumio?

**Comment by lumio** [comment]
Sorry for the late response!
It looks really great. Only problem I see is that the autocomplete is case sensitive.

If I had an item `Green` and search for `green` there would be no match.
Other than that, it looks awesome

**Comment by lumio** [comment]
Awesome! Thanks! I will look into it tomorrow. So far it is great!
@terkelg should I merge it when I have checked it again or do you want to?

**Comment by terkelg** [comment]
Thank you guys! Great feedback @lumio – appreciate it.
I'll check this out in the weekend and merge. High five!

**Comment by creatyvtype** [comment]
Just so y'all know, I looked around at other prompt packages to find this feature and none of them had it. I chose to add it to yours because the code was VERY well organized and so easy to navigate compared to some of the others, so High Five right back at ya!

**Comment by lumio** [comment]
Looks good to me ;) also the multiselect

**Pull request merged**
