### PR TITLE
fix(text-input): make cursor reflect current position

### PR DESCRIPTION
**Pull request by krishna-acondy**
# Issue
#249

# Intent
Make the cursor correctly reflect its current position.

# Implementation
* Added `cursorOffset` field, initialised to `0`.
* Set the `cursorOffset` whenever the cursor is moved either way.
* When rendering, move the cursor by the offset value.

@terkelg I wasn't too sure if the offset can be derived from what's available in `sisteransi.cursor`. If it can, I'm happy to change this implementation.

## Before
https://www.loom.com/share/e338c4cfc6bc42818f914d2bebf72ecc

## After
https://www.loom.com/share/7ffc90963b2943f3a16c039661bc3cbf

### CODE REVIEW

**Comment by krishna-acondy** [comment]
@terkelg /@Wing003 Thoughts on this fix?

**Comment by terkelg** [comment]
Looking good to me. I'll pull and test your commit this weekend

**Comment by terkelg** [comment]
This solution has some problems when deleting. See attached video

https://user-images.githubusercontent.com/2302254/110086858-318e3580-7d93-11eb-9544-c6c71f8bd2c9.mp4

**Comment by krishna-acondy** [comment]
Got it. I'll put in a fix for that ASAP.

**Comment by krishna-acondy** [comment]
@terkelg I think I've covered all the delete scenarios with the last commit. 😅 

https://user-images.githubusercontent.com/2980428/110207186-b489bb80-7e79-11eb-9ac3-25059258b9a7.mov

I've also added some tests to cover the scenarios in question. I'm sure we could be a lot more thorough with those, but that might be something for another PR later on. 🙂

**Comment by krishna-acondy** [comment]
@terkelg Are we happy enough with this fix?

**Comment by terkelg** [comment]
Sorry @krishna-acondy I haven't had time. I'm sure it's good – I'll check and hopefully merge the commit before the week is over

**Comment by krishna-acondy** [comment]
Sounds good, thank you! 🙏🏽

**Comment by terkelg** [comment]
I'm still getting some issues when text is deleted. See attachment 

https://user-images.githubusercontent.com/2302254/111035912-dd332780-841c-11eb-93c4-1c9d3d8c4ab9.mp4

**Comment by krishna-acondy** [comment]
@terkelg I've fixed that in the last commit - we shouldn't have been moving the cursor when it was already at the start.

https://www.loom.com/share/8d75f2b0d2ec44b9912caef47f7d550f

**Comment by krishna-acondy** [comment]
@terkelg Have you had a chance to try this out in the past week?

**Comment by terkelg** [comment]
Hi @krishna-acondy - thank you for the ping. I'm traveling and I'll check later this week

**Comment by krishna-acondy** [comment]
@terkelg Sorry to be reminding again, but it'd be great if you could give this a quick test at some point. I'd really like to get this over the line.

**Comment by terkelg** [comment]
Thank you - looks good. It will be a part of the next release

**Pull request merged**
