### PR TITLE
fix autocomplete fallback

### LINKED ISSUE #121: Fallback not working on autocomplete
Maybe I'm misunderstanding the purpose of fallbacks for autocomplete, but I'm expecting it to come up if I type something that's not one of the choices. Right now, all I see is `undefined`, and I can't figure out how I'd get to see that fallback message at all.

prompts

Is there currently a way to limit an autocomplete type prompt to the predefined choices and/or validate it to that list?

### PR DESCRIPTION
**Pull request by DrunkenPoney**
Fixes #121

### CODE REVIEW

**Comment by lumio** [comment]
Haha, I'm 2h too late with my PR

**Comment by terkelg** [comment]
Awesome, thank you guys! This is a luxury problem. It sounds like #138 is a bit more robust right? On the other hand, it's a bit more code.

**Comment by lumio** [comment]
@DrunkenPoney if you want, you could take parts of my PR to make yours work again.
With my changes at #138 I added string support for the initial value of autocomplete. Not sure if we really want that though.

In any case: @terkelg you decide 😄

**Comment by DrunkenPoney** [comment]
@terkelg #138 is probabl

**Pull request closed without merging**
