### PR TITLE
Add validate function to autocomplete

### PR DESCRIPTION
**Pull request by dvsmedeiros**
add validate function to autocomplete prompt with same behavior of text, password, invisible, number and date prompts

### CODE REVIEW

**Comment by terkelg** [comment]
Thank you so much. I'll have a look at this over the weekend.

**Comment by terkelg** [comment]
Can you update the PR to make sure the prompt line isn't repeated when you hit `return` multiple times on a `false` validate callback? Thank you

**Comment by dvsmedeiros** [comment]
I couldn't reproduce this situation, can you give me a test example?

**Comment by terkelg** [comment]
Yes, I'll get back to you later this week

**Pull request merged**
