### PR TITLE
fix: replace (unprintable) unicode char in select

### PR DESCRIPTION
**Pull request by DanielRuf**
This fixes https://github.com/terkelg/prompts/issues/78

### CODE REVIEW

**Comment by DanielRuf** [comment]
I'm not sure what you mean but this is exactly the character which can not be printed on Windows in the shell. Keep in mind that these are special unicode chars which are not supported by all platforms.

**Comment by DanielRuf** [comment]
Also I guess the win check fails here. At least `cursor` is not used in this case but directly the character. I will change and test if the Windows detection works properly.

**Comment by DanielRuf** [comment]
Changed it according to the other files.

**Comment by terkelg** [comment]
Thanks

**Pull request merged**
