### PR TITLE
Added description option to choices (Fixes #165)

### LINKED ISSUE #165: add description for choice
### Is your feature request related to a problem?

I want set description for each choice, but I not found related options, So I wrote a temporary solution to merge description and title：

``` js
function convertChoices(choices) {
  let pad = 0

  choices.forEach(choice => pad = Math.max(pad, choice.title.length))
  return choices.map(choice => Object.assign({}, choice, {
    title: `${choice.title.padEnd(pad + 1)} - ${choice.description}`
  }))
}
```

### Describe the solution you'd like

Add description for choice, example:

``` js
[
  {
    type: 'select',
    name: 'boilerplate',
    message: 'Select the boilerplate type',
    choices: [
      {
        title: 'ant-design-pro',
        description: 'Create project with an layout-only ant-design-pro boilerplate, use together with umi block.',
        value: 'ant-design-pro'
      },
      {
        title: 'app',
        description: 'Create project with a simple boilerplate, support typescript.',
        value: 'app'
      },
      {
        title: 'block',
        description: 'Create a umi block.',
        value: 'block'
      },
      {
        title: 'library',
        description: 'Create a library with umi.',
        value: 'library'
      },
      {
        title: 'plugin',
        description: 'Create a umi plugin.',
        value: 'plugin'
      }
    ]
  }
]
```

Output:

```
? Select the boilerplate type
  ant-design-pro  - Create project with an layout-only ant-design-pro boilerplate, use together with umi block.
❯ app             - Create project with a simple boilerplate, support typescript.
  block           - Create a umi block.
  library         - Create a library with umi.
  plugin          - Create a umi plugin.
```

### Describe alternatives you've considered

I didn't consider alternatives

### Additional context

None.

### PR DESCRIPTION
**Pull request by DrunkenPoney**
Actually it will duplicate the first lines if the description has more than one line. Though, this problem should be fixed once #168 is merged.

I'm gonna wait for #168 to be merged before doing the same for multiselect. In fact, it's already done for multiselect but I did not push it cause for some reason the first line does not print so I'll wait to see if #168 fixes this problem or if it changes anything.

### CODE REVIEW

**Comment by lumio** [comment]
I'll look into this on the weekend 😃  thank you for your PR though! 👍

**Comment by lumio** [comment]
Gonna wait with the review then, until #168 has been merged

**Comment by terkelg** [comment]
Is this still relevant after #168 has been merged?

**Comment by DrunkenPoney** [comment]
Sorry! I was busy in the last few days. I'm working on it at the moment

**Comment by DrunkenPoney** [comment]
Done! ;)

**Comment by terkelg** [comment]
Thank you! I'm currently traveling. I'm going to merge this and release the next version when I get back 👍

**Pull request merged**
