### PR TITLE
Added onKeypress

### PR DESCRIPTION
**Pull request by DrunkenPoney**
Added an onKeypress param to the prompts.
See changes in readme for more details.

### CODE REVIEW

**Comment by terkelg** [comment]
Thanks @DrunkenPoney! I'll take a look at the new PRs over the weekend. Appreciate it!

**Comment by terkelg** [comment]
I think this can be implemented in a even simpler way in [`Prompts.js`](https://github.com/terkelg/prompts/blob/master/lib/prompts.js#L11). All prompts already fire a `state` event. Maybe call it onStateChange?

**Comment by DrunkenPoney** [comment]
Yep! You're right! I thought onState was triggered only when a prompt was closed (aborted or submitted).

**Comment by DrunkenPoney** [comment]
@terkelg I just thought that `onState()` is not exactly triggered on key press so it can't receive the key which has been pressed. I thought maybe someone might want to behave differently when a specific key is pressed or might want to do any other action when a specific key is pressed. Such things are not possible with the actual onState and I think maybe onState could be modified to make it possible.

For example, I wanted to use an `autocomplete` prompt for suggestion only so pressing  <kbd>tab</kbd> would append the selection to the current value but actually I think pressing <kbd>tab</kbd> submits the value entered or selected.

**Comment by terkelg** [comment]
I see - you want to overwrite default keypress behavior. I'm open to this if it's possible to change or modify the `onState()` method/event or somehow implement this in very simple way. I don't know what such implementation would look like though.

**Pull request closed without merging**
