### PR TITLE
Remove support for EOL Node versions <14

### PR DESCRIPTION
**Pull request by joeykilpatrick**
Removes support for Node.js versions `6.x.x` and `8.x.x`.

Node.js release schedule [here](https://github.com/nodejs/Release).

Transition from Travis CI to GitHub Actions for testing for Node versions >= 14.

Benefits:

- Removes `babel` dependencies and transpilation step
- Allows for use of newer Node features (e.g. optional chaining, `Array.at`, nullish coalesce)

@terkelg

### CODE REVIEW

**Comment by terkelg** [comment]
Amazing – thank you @joeykilpatrick

**Comment by terkelg** [comment]
@lukeed can you have a look at this real quick to confirm everything looks alright?

**Comment by terkelg** [comment]
Will be a part of the next release 👍

**Comment by lukeed** [comment]
chiming in for 2s, this will have to be a 3.0 release due to the minimum Node version bump :)

**Comment by riderx** [comment]
When can we expect a release the latest on npm is 2021 ?

**Pull request merged**
