### PR TITLE
Added date prompt

### PR DESCRIPTION
**Pull request by gebeto**
I've add `date` prompt which can be improved in the future
It can be added keyboard input later

It is relative to #109 issue

How are you creates gifs with examples? I can create it and add it to the pull request

### CODE REVIEW

**Comment by terkelg** [comment]
That's so awesome @gebeto! Thank you so much. I'll have a look at it over the weekend. Don't worry about the gifs, I'll do that (I have an After Effects template).

Thank you for contributing to Prompts. It's really cool with new prompt types!

**Comment by terkelg** [comment]
Looks really good @gebeto. I like it a lot. This is definitely going to be merged into Prompts. Thank you so much for also updating the documentation, tests and JSDocs. Superb! 👍 

Here are some ideas for even better UX:
- Make it possible to cycle year/date/month with `tab`.
- Make it possible to type numbers - like in the `Number` prompt.
- Option to change format (`mm/dd/yy`, `dd/mm/yy`).
- Possible `validate` function like in the `Number` prompt?

Similar to [date-prompt](https://github.com/derhuerst/date-prompt). Let me know if you're up for some of it. I can possibly help out with some of it in the future.

**Comment by gebeto** [comment]
Okay! I will do that a little bit later and add it to this pull request :)

**Comment by DrunkenPoney** [comment]
@terkelg I think this PR can be closed now since everything is in #141

**Comment by gebeto** [comment]
Yep, please close it :)

**Pull request closed without merging**
